### ISSUE TITLE
Properties with the dot in the name are not handled correcty

### ISSUE THREAD

**Issue by alexandervain** [kibertoad/protobuf-fieldmask#1]
## Problem
Given the following object having a property with `.` in its name (_`b.d`_): 
```
{
  f: {
    b: {
      d: 1
    },
    'b.d': 33
  }
}
```
the `generateFieldMask` will produce this mask: `["f.b.d","f.b.d"]` where we can't distinguish between 2 different properties.

## Version
Version: 1.0.2

## Suggested solution
Escaping of the `.` and `\` characters would solve the issue. So the expected result for the `generateFieldMask` invocation with the above object would be: `["f.b.d","f.b\\.d"]`

**Note**: the `applyFieldMask` should change accordingly to respect the escaped paths.

**Comment by alexandervain** [comment]
@kibertoad proposal for the solution implementation - https://github.com/kibertoad/protobuf-fieldmask/pull/2

**Comment by kibertoad** [comment]
Released in 1.1.0!
