### ISSUE TITLE
Does not work with objects with no prototype

### ISSUE THREAD

**Issue by satazor** [kibertoad/protobuf-fieldmask#5]
Objects created with `Object.create(null)` do not work well with this package. The reason is that this packages uses `hasOwnProperty` which is not available in these cases.

Changing to `Object.protototype.hasOwnProperty.call(obj, prop)` should work. Alternatively you may use lodash `has`.

**Comment by kibertoad** [comment]
@satazor could you send a pr with the switch to the prototype solution?

**Comment by satazor** [comment]
Yes will do.

**Comment by satazor** [comment]
@kibertoad https://github.com/kibertoad/protobuf-fieldmask/pull/6
